import functools
import os
import re
import urllib.request

URL = "https://mirrors.ctan.org/macros/unicodetex/latex/unicode-math/unicode-math-table.tex"
INPUT = "unicode-math-table.tex"
OUTPUT = "Sources/UnicodeMath/Symbols.swift"

if not os.path.exists(INPUT):
    urllib.request.urlretrieve(URL, INPUT)

mapping = []

with open(INPUT) as f:
    regex = re.compile(r'\\UnicodeMathSymbol\{"(\w{5})\}\{\\(\w+)\s*\}\{\\(\w+)\}\{(.+)\}\%.*$')

    for line in f:
        m = regex.match(line)
        if m is None:
            continue

        codepoint, command, kind, description = m.group(1, 2, 3, 4)
        mapping.append((int(codepoint, 16), command, description))

with open(OUTPUT, "w") as f:
    width = functools.reduce(lambda ell, tup: max(ell, len(tup[1])), mapping, 0)

    f.write("// This file is generated by gen-symbols.py\n")
    f.write("// Do not edit by hand!\n\n")
    f.write("public let MATH_SYMBOLS: [MathSymbol] = [\n")
    for cp, cmd, desc in mapping:
        f.write('    .init("\\u{{{cp:05x}}}", {cmd:' '<{width}} "{desc}"),\n'.format(cp=cp,
                                                                                     cmd=f'"{cmd}",',
                                                                                     width=width + 2,
                                                                                     desc=repr(desc)[1:-1]))
    f.write("];\n")
